### ISSUE TITLE
White macOS icon

### ISSUE THREAD

**Issue by mre** [mre/timelapse#27]
## Feature Request Type

- [ ] Core functionality
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Maybe there is a way to detect if a user is on a dark theme on macOS and use a white icon accordingly?

**Comment by cmangla** [comment]
As a temporary fix, you could remove the alpha pixels from the icons and replace them with white. This way they'll be visible in a black background.

**Comment by cmangla** [comment]
> As a temporary fix, you could remove the alpha pixels from the icons and replace them with white. This way they'll be visible in a black background.

See https://stackoverflow.com/questions/28937084/imagemagick-remove-alpha-component-replace-all-intermediate-alpha-pixel-with-s

**Comment by mre** [comment]
This is now done in `master`. Turns out there is a simple way to check:

```python
def dark_mode():
    return NSUserDefaults.standardUserDefaults().stringForKey_('AppleInterfaceStyle') == "Dark"
```

Thanks for the support @cmangla. 😊
