### ISSUE TITLE
Use ffmpeg from user path instead of specifying one

### ISSUE THREAD

**Issue by cmangla** [mre/timelapse#29]
In Encoder, `ffmpeg` might not be at the path we've hardcoded.

**Comment by cmangla** [comment]
This is for https://github.com/mre/timelapse/blob/2fad98e309d0965287f79cc619d31905fe340268/timelapse/encoder.py#L44

I'm about to submit a pull request.

**Comment by mre** [comment]
This should be fixed now. See the comment over at #30.
I hope it works for everyone. Closing this to keep the issue tracker up-to-date, but please reopen if you encounter any problems. Credits go to @cmangla for fixing it.
