### ISSUE TITLE
Use Python 3 types

### ISSUE THREAD

**Issue by mre** [mre/timelapse#31]
## Feature Request Type

- [X] Core functionality
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

We should use types wherever we can to make refactoring easier. If someone wants to give it a try, please go ahead. I can provide support if needed. 😊

**Comment by orcutt989** [comment]
@mre Do you mean Python 3.5 and lower type comments like -
```python
var=1 #int 
``` 
or Python 3.6 typing
```python
var: int=1
```
Reference
https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html#variables

**Comment by mre** [comment]
True, I meant 3.6 types. We should upgrade to that. 😅
Please go ahead if you like to work on that. Thanks!

**Comment by orcutt989** [comment]
@mre I'm on it.

**Comment by mre** [comment]
> Did we want function typing too? 

Yup, that would be great. I saw that you already did that in your PR. 😄
