### ISSUE TITLE
Release 1.0 🎉

### ISSUE THREAD

**Issue by mre** [mre/timelapse#38]
Timelapse is finally mature enough to create a 1.0 version. It only took a decade. 😊
That's a major milestone so I was thinking about announcing it on Twitter, https://www.reddit.com/r/Python/ and https://news.ycombinator.com/show.
Planning to write a little blog post to celebrate this achievement.
If you want to help me with that, check out https://hackmd.io/gTiX8GjwRqaC3_CCQOn2Jw.

If you find any last-minute showstoppers, please mention them here or create a separate issue.
Thanks to all the contributors so far!

@seleregb
@cmangla
@ShaneCreedon 
@orcutt989 
@gkpln3 
@abnerpc 
@ShreyaPrabhu 
@Kerl1310 

Make sure to add your twitter/github handle to the Credits section of the document. 😉 🍷

**Comment by cmangla** [comment]
@mre I suppose your blog post is a kind of "timelapse" on it's own, summarising the slow and steady 10 year development into a post that can be read in a few minutes. Perhaps you can write something like that near the opening of the post :)

**Comment by cmangla** [comment]
and somewhere in the middle, you could write something like "... and much time-lapsed before ...". I like puns :).

**Comment by mre** [comment]
Uh! Great idea. You can actually edit the document if you like. 😉

**Comment by cmangla** [comment]
I made some edits there but I hope it is easy to revert them if you don't like the rephrasing.

**Comment by mre** [comment]
Thanks for the edits! No worries, everything would be quite easy to revert, but I don't think it's needed. 👍

**Comment by cmangla** [comment]
> Thanks for the edits! No worries, everything would be quite easy to revert, but I don't think it's needed. 👍

@mre Great! All looks good to me. Good luck with the 1.0 release and the publicity!

**Comment by seleregb** [comment]
@mre It looks good to me. 👍

**Comment by mre** [comment]
Thanks for the feedback so far. Aiming to publish this tomorrow. Until then, feel free to edit the doc.

**Comment by mre** [comment]
We did it! 1.0 is out. 
https://endler.dev/2020/timelapse/
Thanks everyone for making this happen.
Here's to the next ten years. 🍾 😆 

![(GIF Image, 384 × 216 pixels)](https://user-images.githubusercontent.com/175809/73793722-3e62e300-47a7-11ea-8034-d693fcce5655.gif)
