### ISSUE TITLE
Timelapse Error [Errno 2] No such file or directory: 'ffmpeg':'ffmpeg'

### ISSUE THREAD

**Issue by ItsThompson** [mre/timelapse#40]
## The Bug
When stopping the timelapse and processing the timelapse, this error come up.

## System Information

 - Operating system: MacOS Mojave 10.14.5
 - Software version: V1

<img width="328" alt="Screenshot 2020-02-17 at 1 22 37 PM" src="https://user-images.githubusercontent.com/33135895/74625816-9545c080-5188-11ea-8331-cbdfb5819a29.png">

**Comment by ItsThompson** [comment]
Update: Apologies, I looked more into the code and installed ffmpeg and it worked. I made a fork that added your "not_found_msg" onto the Timelapse Error Notification.
Heres the link: https://github.com/ItsThompson/timelapse/blob/master/timelapse/encoder.py
Hope it helps.

**Comment by mre** [comment]
Sorry that you had to go through those troubles. I've extended the instructions in the `README.md` a bit to make that easier for the next person.
