### ISSUE TITLE
Invalid filename: __init.py__ 

### ISSUE THREAD

**Issue by estysdesu** [mre/timelapse#43]
# Invalid filename: \_\_init.py\_\_

## Why
The idea was to make the `./timelapse` folder a [Python package](https://docs.python.org/3.8/tutorial/modules.html#packages) I'm sure. But, `__init.py__` is not the correct form. 

## Fix
It should be `__init__.py`.

##Supporting Evidence
[The Python documentation on packages](https://docs.python.org/3.8/tutorial/modules.html#packages)

**Comment by mre** [comment]
Oh, nice catch! Thanks. 🚀
