### ISSUE TITLE
Add travis config

### ISSUE THREAD

**Issue by mre** [mre/timelapse#5]
Would be nice to have a basic travis config for this project, which would build the project on every pull request. That might form the basis for #4.

**Comment by seleregb** [comment]
I can set this up for you 😄

**Comment by mre** [comment]
That would be great. 🎉

**Comment by seleregb** [comment]
What python version are you targeting?

**Comment by mre** [comment]
I'd say let's try with Python 3 and go from there.

**Comment by seleregb** [comment]
Okay

**Comment by mre** [comment]
Thanks again @seleregb for fixing this. Closing as this is done.
