### ISSUE TITLE
Nothing happens at all

### ISSUE THREAD

**Issue by jcayzac** [mre/timelapse#50]
macOS Catalina 10.15.5 (19F101), running Timelapse 1.0.1.

Tapping `Start recording` doesn't do anything (no notification either).
Tapping `Stop recording` also doesn't do anything (no notification, nothing saved anywhere).

The app also doesn't seem to request permission to access the filesystem, which might explain why nothing happens.

**Comment by jcayzac** [comment]
Screenshots do get created in `~/Pictures/timelapse/Session-####`, though.

**Comment by mre** [comment]
That's odd. I'm on 10.15.6 here. Can you start it from the commandline and see what happens?

**Comment by jcayzac** [comment]
ffmpeg was not in the path
