### ISSUE TITLE
Make this an app

### ISSUE THREAD

**Issue by mre** [mre/timelapse#6]
Many people don't know how to use the command-line. Nevertheless, they would still like to use this project for recording time-lapses. Would be nice if we made a runnable macOS app out of the code here. This way, people could simply start the application with a click and start recording.

Instructions here: https://py2app.readthedocs.io/en/latest/

**Comment by mre** [comment]
Sure, that would be very nice of you. Please go ahead @mepda 😊

**Comment by mre** [comment]
This is now done in master. 🎉 The first app release after 10 years. 😆 
Updated the docs accordingly.
@cmangla, @mepda, @gkpln3: please test it if you find the time.

**Comment by gkpln3** [comment]
Will do, great job!

**Comment by cmangla** [comment]
Wow, great job @mepda and @mre !

I am guessing the main commit related to this issue (#6) is 6a1b942 ? Just wanted to note that here for records, since I couldn't find a related pull request.

**Comment by cmangla** [comment]
I did some very basic tests and it ran flawlessly!

After unzipping, I ran the app, and MacOS gave the usual warnings about it being unsigned. We might want to document how to allow the application to run from the "Security & Privacy" preferences pane.

I'm using a dark background and so the new white icons were a charm. The notifications were also great.

**Comment by cmangla** [comment]
While reviewing, I found that we've accidentally hardcoded the path to `ffmpeg` in one place. See issue #29 and PR #30 .

**Comment by mre** [comment]
This is fixed now. 🎉 Thanks for all the input folks. Closing.
