### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by mepda** [mre/timelapse#7]
I tried running this as a Python 3 and Python 2 program and got problems with both. 
Here's the error for python3:
```Traceback (most recent call last):
  File "timelapse.py", line 8, in <module>
    from encoder import Encoder  # Creates timelapse video
  File "/Users/hector/Desktop/practice/63-hacktoberfest/01-timelapse/timelapse/encoder.py", line 42
    print "\n\nabout to execute:\n%s\n\n" % ' '.join(command)
                                        ^
SyntaxError: invalid syntax```

And here's the error message for python2:
```Traceback (most recent call last):
  File "timelapse.py", line 33, in <module>
    class Timelapse(NSObject):
  File "timelapse.py", line 103, in Timelapse
    @objc.python_method
AttributeError: 'module' object has no attribute 'python_method'```

**Comment by mre** [comment]
Oh my. Sorry 'bout that. Fixed the print statements for Python 3 in https://github.com/mre/timelapse/commit/d7a5ae0950352940afb2ab851b3cc6ff4f17f7e6. Could you please try again? 😅

**Comment by mepda** [comment]
Okay, I compiled it, but when I run ```python recorder.pyc``` I'm getting 
```RuntimeError: Bad magic number in .pyc file```
How should I proceed?

**Comment by mre** [comment]
Did you see the usage instructions in the `README.md`?

**Comment by mepda** [comment]
Yeah, I installed the dependencies using pip, then ran the .py file, but didn't see any icon pop up.

**Comment by mre** [comment]
Because the `pyc` files are object code files not meant to be executed directly. 😉

**Comment by mre** [comment]
Hum... that's strange. Any output? Which macOS version are you using?

**Comment by mepda** [comment]
High Sierra 10.13.6

**Comment by mepda** [comment]
<img width="766" alt="screen shot 2018-10-28 at 1 45 44 am" src="https://user-images.githubusercontent.com/10606510/47606800-040e8000-da53-11e8-97ca-3a92cf7c3517.png">

**Comment by mepda** [comment]
<img width="803" alt="screen shot 2018-10-28 at 1 46 51 am" src="https://user-images.githubusercontent.com/10606510/47606813-3ddf8680-da53-11e8-8803-ccdf88a0ed52.png">

**Comment by mepda** [comment]
tried with both python 2 and python 3

**Comment by mre** [comment]
Thanks for the feedback. Looks like the project isn't really Python 3 compatible yet. Especially the exception handling has to be adjusted. Will do that.

**Comment by mepda** [comment]
👍 Let me know if theres anything else I can help with

**Comment by mre** [comment]
Created a new ticket for that in #21. Closing this. Thanks for your feedback @mepda. 👍

**Comment by mre** [comment]
Quick update: we got support for Python 3.7 thanks to #21. Github Actions pipeline is here: https://github.com/mre/timelapse/blob/master/.github/workflows/pythonapp.yml
